require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Lint/SuppressedException:
  AllowComments: true

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/routes.rb"
    - "db/migrate/*"

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc"]

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc"]
  Exclude:
    - "db/migrate/*"

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Max: 20
  CountAsOne: ["array", "hash", "heredoc"]

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ImplicitSubject: 
  EnforcedStyle: single_statement_only

Style/Documentation:
  Enabled: false
